## Project Scenario:

An international firm that is looking to expand its business in different countries across the world has recruited you. You have been hired as a junior Data Engineer and are tasked with creating a script that can extract the list of the top 10 largest economies of the world in descending order of their GDPs in Billion USD (rounded to 2 decimal places), as logged by the International Monetary Fund (IMF).

In [55]:
import numpy as np
import pandas as pd

In [56]:
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn
warnings.filterwarnings('ignore')

In [57]:
url="https://web.archive.org/web/20230902185326/https://en.wikipedia.org/wiki/List_of_countries_by_GDP_%28nominal%29"

In [58]:
tables = pd.read_html(url)

In [59]:
df = tables[3]
print(df.shape)

(214, 8)

In [60]:
# Replace the column headers with column numbers
df.columns = range(df.shape[1])

In [61]:
df2 = df[[0, 2]]
df2

                 0          2
0            World  105568776
1    United States   26854599
2            China   19373586
3            Japan    4409738
4          Germany    4308854
..             ...        ...
209       Anguilla          —
210       Kiribati        248
211          Nauru        151
212     Montserrat          —
213         Tuvalu         65

[214 rows x 2 columns]

In [62]:
# Top 10 economies
df2 = df2.iloc[1: 11]
df2

                 0         2
1    United States  26854599
2            China  19373586
3            Japan   4409738
4          Germany   4308854
5            India   3736882
6   United Kingdom   3158938
7           France   2923489
8            Italy   2169745
9           Canada   2089672
10          Brazil   2081235

In [63]:
df2.columns = ['Country', 'GDP (Million USD)']
df2

           Country GDP (Million USD)
1    United States          26854599
2            China          19373586
3            Japan           4409738
4          Germany           4308854
5            India           3736882
6   United Kingdom           3158938
7           France           2923489
8            Italy           2169745
9           Canada           2089672
10          Brazil           2081235

In [64]:
# Convert million to billion USD
df2['GDP (Million USD)'] = ((df2['GDP (Million USD)']).astype(int) / 1000)
df2['GDP (Million USD)'] = np.round(df2['GDP (Million USD)'], 2)
df2.rename(columns={'GDP (Million USD)': 'GDP (Billion USD)'}, inplace=True)
df2

           Country  GDP (Billion USD)
1    United States           26854.60
2            China           19373.59
3            Japan            4409.74
4          Germany            4308.85
5            India            3736.88
6   United Kingdom            3158.94
7           France            2923.49
8            Italy            2169.74
9           Canada            2089.67
10          Brazil            2081.24

In [65]:
#Load Dataframe to CSV file
df2.to_csv('Largest Economies.csv', index = False)