## Project Description
In this project, you will build a Python web scraper that collects job listings from the Fake Python Jobs website. The scraper will extract information such as the job title, company name, location, and a link to the full job description.


Because this site is intentionally structured for learning, it’s perfect for beginners. You can focus on understanding HTML structure, selecting elements, and processing data without having to deal with complex anti-scraping protections or legal restrictions.

In [43]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [ ]:
url = 'https://realpython.github.io/fake-jobs/'

In [ ]:
r = requests.get(url)

In [ ]:
html_contents = r.text

In [ ]:
soup = BeautifulSoup(r.text, 'html.parser')

To handle missing cases, need to iterate through the positng one by one and extract the details. If any data are missing append none instead of returning different lengths of dataframe. Search only in the relevant container class.

In [ ]:
# Search for results container
results_container = soup.find(id='ResultsContainer')
# Search for individual job postings
job_postings = results_container.find_all('div', class_='card-content')

In [62]:
job_titles = []

# Extract job titles and turn it into a dataframe
for job_posting in job_postings:
  title_element = job_posting.find('h2', class_='title is-5')
  if title_element:
    job_title = title_element.text.strip()
  else:
    job_title = None
  job_titles.append(job_title) # Add each extracted job title to the list

# Create a DataFrame
df1 = pd.DataFrame({'Job Title': job_titles})
display(df1.head()) # Display the first 5 rows of the DataFrame

df1.info()

                 Job Title
0  Senior Python Developer
1          Energy engineer
2          Legal executive
3   Fitness centre manager
4          Product manager

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 1 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Job Title  100 non-null    object
dtypes: object(1)
memory usage: 932.0+ bytes

In [58]:
company_names = []
for job_posting in job_postings:
  company_element = job_posting.find('h3', class_ = 'subtitle is-6 company')
  if company_element:
    company_name = company_element.text.strip()
  else:
    company_name = None
  company_names.append(company_name)

df2 = pd.DataFrame({'Company Name': company_names})

In [59]:
locations = []
for job_posting in job_postings:
  location_element = job_posting.find('p', class_ = 'location')
  if location_element:
    location = location_element.text.strip()
  else:
    location = None
  locations.append(location)

df3 = pd.DataFrame({'Location': locations})

In [60]:
urls = []
for job_posting in job_postings:
  url_element = job_posting.find('a', string=lambda text: text and text.lower() == 'apply')
  if url_element:
    url = url_element.get('href')
  else:
    url = None
  urls.append(url)

df4 = pd.DataFrame({'URL': urls})

In [61]:
df1.info()
df2.info()
df3.info()
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 1 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Job Title  100 non-null    object
dtypes: object(1)
memory usage: 932.0+ bytes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 1 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Company Name  100 non-null    object
dtypes: object(1)
memory usage: 932.0+ bytes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 1 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Location  100 non-null    object
dtypes: object(1)
memory usage: 932.0+ bytes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   URL     100 non-null    object
dtypes: object(1)
memory usage: 932.0+ bytes

In [63]:
result = pd.concat([df1, df2, df3, df4], axis=1)
result.head()

,Job Title,Company Name,Location,URL
0,Senior Python Developer,"Payne, Roberts and Davis","Stewartbury, AA",https://realpython.github.io/fake-jobs/jobs/se...
1,Energy engineer,Vasquez-Davidson,"Christopherville, AA",https://realpython.github.io/fake-jobs/jobs/en...
2,Legal executive,"Jackson, Chambers and Levy","Port Ericaburgh, AA",https://realpython.github.io/fake-jobs/jobs/le...
3,Fitness centre manager,Savage-Bradley,"East Seanview, AP",https://realpython.github.io/fake-jobs/jobs/fi...
4,Product manager,Ramirez Inc,"North Jamieview, AP",https://realpython.github.io/fake-jobs/jobs/pr...

In [64]:
result.to_csv('job_listings.csv', index=False)